### ISSUE TITLE
JavaScript Bootcamp Kris Kuiper

### ISSUE THREAD

**Issue by kriskuiper** [cmda-bt/js-bootcamp-18-19#1]
# My Introduction
I eat code for breakfast.

## Name
Kris Kuiper

## Class
209

## About me
I am very passionate about everything that's (related to) Front End Development.

## Goals
To get better at writing code and learn about Backend Development. Also I would not only like to develop myself as a professional but also as a person.

## Skill level
Probably somewhere between 'Intermediate' and 'Advanced'.

## GitHub username
https://github.com/kriskuiper

## GitHub repository
https://github.com/kriskuiper/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
