### ISSUE TITLE
js-bootcamp Emma Oudmaijer

### ISSUE THREAD

**Issue by emmaoudmaijer** [cmda-bt/js-bootcamp-18-19#10]
# My Introduction
Ik ben Emma en wil graag beter worden met het gebruiken van javascript.

## Name
Emma Oudmaijer`

## Class
Tech2

## About me
Ik sport veel en ben erg gemotiveerd.

## Goals
Beter worden met javascript.

## Skill level
Beginner

## GitHub username
emmaoudmaijer

## GitHub repository
https://github.com/emmaoudmaijer/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

You're repo does feel a bit empty.. :)
