### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by TomasStolp** [cmda-bt/js-bootcamp-18-19#100]
# My Introduction

## Name
Tomas Stolp

## Class
Tech 3

## About me
Ik houd van METAL! \m/

## Goals
Basisprincipes programmeren doorgronden;
Progressive Enhancement leren toepassen;
Netter en efficiëntere code opleveren;

## Skill level
Een intermediate omdat ik al veel met front en backend heb gedaan. Ik heb alleen het gevoel dat de manier waarop ik code toepas lang niet altijd de beste manier is. Ik zou mij daarin graag verbeteren. 

## GitHub username
[TomasS666](https://github.com/TomasS666)

## GitHub repository
https://github.com/TomasS666/JS-Bootcamp-Exercises

**Comment by dandevri** [comment]
👋 Hi Tomas, the link to your repo has been added to the admin sheet. Thanks! 🎉
