### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/js-bootcamp-18-19#101]
# My Introduction

## Name
Marissa Verdonck

## Class
Tech 4 

## About me
Ik word ontzettend blij van skiën! Maar ook als ik een code schrijf die werkt.

## Goals
Beter worden in Javascript en werken met data.

## Skill level
Beginner, ik heb alleen de kennis van wat we bij CMD hebben geleerd.

## GitHub username
[marissaverdonck](https://github.com/marissaverdonck)

## GitHub repository
[GitHub repository](https://github.com/marissaverdonck/JS-Bootcamp-Exercises)

**Comment by dandevri** [comment]
👋 Hi Marissa, the link to your repo has been added to the admin sheet. Thanks! 🎉

Where do you usually go skiing? ⛷
