### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by marissaverdonck** [cmda-bt/js-bootcamp-18-19#102]
# Exercises

## Name
Marissa Verdonck

## Class
Tech 4

## GitHub username
[marissaverdonck](https://github.com/marissaverdonck)

## Bootcamp exercises
[Bootcamp exercises](https://github.com/marissaverdonck/JS-Bootcamp-Exercises/tree/master/Week%201)

## Bootcamp notes
[Aantekeningen](https://github.com/marissaverdonck/JS-Bootcamp-Exercises/tree/master/Aantekeningen)

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
