### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/js-bootcamp-18-19#104]
# My Introduction

I might already submit this issue a week ago. However I am not sure if I did it in the right way, fairly new to GitHub, but getting the hang of it after a few lectures, thanks!

## Name
Robert Hoekstra

## Class
214 (tech 3)

## About me
I am a 26 year old barista that drives around in a van. I love aviation and would like to become
an UX designer at an airliner/

## Goals
Learn more about JavaScript, about it's potention and usefullness

## Skill level
Begger

## GitHub username
https://github.com/robert-hoekstra

## GitHub repository
https://github.com/robert-hoekstra/BlokTech/tree/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Robert, the link to your repo has been added to the admin sheet. Thanks! 🎉

What's your favorite brewing method? ☕️
