### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by jor-s** [cmda-bt/js-bootcamp-18-19#107]
# My Introduction

## Name
Jordy Sahit

## Class
214/Tech-4

## About me
I like to go to the gym. 

## Goals
To be able to make a fully functioning website with JS and HTML/CSS.

## Skill level
Beginner.

## GitHub username
https://github.com/sahitj001

## GitHub repository
https://github.com/sahitj001/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Jordy, the link to your repo has been added to the admin sheet. Thanks! 🎉
