### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by jor-s** [cmda-bt/js-bootcamp-18-19#108]
# Exercises

## Name
Jordy Sahit

## Class
214/Tech-4

## GitHub username
https://github.com/sahitj001

## Bootcamp exercises
https://github.com/sahitj001/js-bootcamp/blob/master/week%201/exercises%20week%201.js

## Bootcamp notes
Er zijn verschillende soorten types. Deze zijn: numbers, strings en booleans. Elke waarde definieert een type. 17 is bijvoorbeeld een nummer en is 'hallo' een string. Verder kan je waardes aanpassen met operators. Operators zijn: +, -, /, %, &.

**Comment by jor-s** [comment]
Ik ben een gedeelte van mijn samenvatting vergeten. Er zijn verschillende soorten statements (if, else en switch) en loops zoals while, for en do. Je kan functies parameters meegeven zodat je die waardes kan aanpassen om een resultaat uit jouw functie te krijgen.

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
