### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by KarinCheng** [cmda-bt/js-bootcamp-18-19#109]
# My Introduction

## Name
Karin Cheng

## Class
Tech 4

## About me
I like animals, especially dogs.

## Goals
Getting better at coding.

## Skill level
Beginner

## GitHub username
https://github.com/KarinCheng

## GitHub repository
https://github.com/KarinCheng/Tech

**Comment by dandevri** [comment]
👋 Hi Karin, the link to your repo has been added to the admin sheet. Thanks! 🎉
