### ISSUE TITLE
jsBootcamp - Sajjad Ali

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/js-bootcamp-18-19#11]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Sajjad Ali

## Class
Klas 202

## Goals
Graag wil ik beter worden in javascript gedurende dit project

## Skill level
Nog steeds beginner

## GitHub username
https://github.com/Sajjad0405

## GitHub repository
https://github.com/Sajjad0405/js-bootcamp

**Comment by Sajjad0405** [comment]
https://github.com/Sajjad0405/js-bootcampRepository

**Comment by dandevri** [comment]
Can you fill in your information?

The link to your repository doesn't work 🤷‍♂️

**Comment by Sajjad0405** [comment]
Working link -> https://github.com/Sajjad0405/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
