### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by KarinCheng** [cmda-bt/js-bootcamp-18-19#110]
# Exercises

## Name
Karin Cheng

## Class
Tech 4

## GitHub username
https://github.com/KarinCheng

## Bootcamp exercises
https://github.com/KarinCheng/Tech/blob/master/Week1/Lesson1.js

## Bootcamp notes
![IMG_20190423_130625](https://user-images.githubusercontent.com/43671651/56576673-4d3a2980-65c9-11e9-9551-64d148620b31.jpg)
![IMG_20190423_130642](https://user-images.githubusercontent.com/43671651/56576656-44495800-65c9-11e9-91c7-78f0fbdf2c4a.jpg)
![IMG_20190423_130652](https://user-images.githubusercontent.com/43671651/56576657-44495800-65c9-11e9-9c25-dc19e193406e.jpg)
![IMG_20190423_130705](https://user-images.githubusercontent.com/43671651/56576658-44495800-65c9-11e9-9018-47a7ec5ee86e.jpg)
![IMG_20190423_130709](https://user-images.githubusercontent.com/43671651/56576659-44e1ee80-65c9-11e9-82f8-89bebf119edc.jpg)
![IMG_20190423_130734](https://user-images.githubusercontent.com/43671651/56576660-44e1ee80-65c9-11e9-9535-5fafc2285b26.jpg)
![IMG_20190423_130738](https://user-images.githubusercontent.com/43671651/56576661-44e1ee80-65c9-11e9-8ad3-b397bfacbfd5.jpg)
![IMG_20190423_130748](https://user-images.githubusercontent.com/43671651/56576662-44e1ee80-65c9-11e9-9962-063e36a67b03.jpg)

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
