### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by smithr002** [cmda-bt/js-bootcamp-18-19#111]
# My Introduction

## Name
Robyn Smith

## Class
Tech 3

## About me
I like dancing and having fun with friends

## Goals
Learning more JavaScript

## Skill level
beginner

## GitHub username
smithr002

## GitHub repository
https://github.com/smithr002/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Robyn, the link to your repo has been added to the admin sheet. Thanks! 🎉
