### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by smithr002** [cmda-bt/js-bootcamp-18-19#112]
# Exercises

## Name
Robyn Smith

## Class
Tech 3

## GitHub username
smithr002

## Bootcamp exercises
https://github.com/smithr002/js-bootcamp/blob/master/l1-chessboard.js
https://github.com/smithr002/js-bootcamp/blob/master/l1-fizzbuzz.js
https://github.com/smithr002/js-bootcamp/blob/master/l1-looping-a-triangle.js
https://github.com/smithr002/js-bootcamp/blob/master/l2-bean-counting.js
https://github.com/smithr002/js-bootcamp/blob/master/l2-minimum.js
https://github.com/smithr002/js-bootcamp/blob/master/l2-sum-of-a-range.js
https://github.com/smithr002/js-bootcamp/blob/master/l3-flattening.js

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
