### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by lennartdeknikker** [cmda-bt/js-bootcamp-18-19#113]
# My Introduction

Ik hou van reizen, Netflix etc.

## Name
Lennart de Knikker

## Class
212

## About me
Ik doe aan vliegvissen.

## Goals
Beter worden in JavaScript en dit leren implementeren.

## Skill level
Intermediate

## GitHub username
https://github.com/lennartdeknikker

## GitHub repository
https://github.com/lennartdeknikker/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Lennart, the link to your repo has been added to the admin sheet. Thanks! 🎉

What are you currently watching on Netflix? 🎞
