### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by benl95** [cmda-bt/js-bootcamp-18-19#116]
# My Introduction

## Name
Ben Langenberg

## Class
Tech 3

## About me
23 jaar en woont in Zaandam

## Goals
Javascript leren en toepassen

## Skill level
Beginner

## GitHub username
https://github.com/benl95

## GitHub repository
https://github.com/benl95/JS-Bootcamp.git

**Comment by dandevri** [comment]
👋 Hi Ben, the link to your repo has been added to the admin sheet. Thanks! 🎉
