### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by OlafDs** [cmda-bt/js-bootcamp-18-19#118]
# My Introduction
Olaf - A Hardworking CMD Student 

## Name
Olaf Driessen

## Class
TECH 3

## About me
I live in Mijdrecht. I'm 21 years old. My hobbies are waterpolo, gaming, chilling with friends and going out to party

## Goals
That i know what i'm exatly  doing with the code and that i can explain what i programmed.

## Skill level
intermediate. I know the basic stuff but i want to know more about the advanced stuff and be more secure about JS coding

## GitHub username
https://github.com/OlafDs

## GitHub repository
https://github.com/OlafDs/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Olaf, the link to your repo has been added to the admin sheet. Thanks! 🎉

What games are you playing? 🎮
