### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by robert-hoekstra** [cmda-bt/js-bootcamp-18-19#120]
# My Introduction

## Name
Robert Hoekstra

## Class
214 (Tech3)

## About me
I want to become a UX-Designer

## Goals
Having a better understanding of JavaScript and being able to write and think like code.

## Skill level
Beginner

## GitHub username
robert-hoekstra

## GitHub repository
https://github.com/robert-hoekstra/js-bootcamp

**Comment by dandevri** [comment]
Duplicate of #104
