### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by joeriBouwman25** [cmda-bt/js-bootcamp-18-19#124]
# My Introduction

## Name
Joeri Bouwman

## Class
Tech-3

## About me
I like music

## Goals
Becoming a JavaScript master

## Skill level
Intermediate

## GitHub username
joeriBouwman25

## GitHub repository
https://github.com/joeriBouwman25/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Joeri, the link to your repo has been added to the admin sheet. Thanks! 🎉
