### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by joeriBouwman25** [cmda-bt/js-bootcamp-18-19#125]
# Exercises

## Name
Joeri Bouwman
## Class
Tech-3

## GitHub username
joeriBouwman25

## Bootcamp exercises
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l1-chessboard.js
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l1-fizzbuzz.js
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l1-looping-a-triangle.js
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l2-bean-counting.js
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l2-minimum.js
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l2-sum-of-a-range.js
https://github.com/joeriBouwman25/js-bootcamp/blob/master/l3-flattening.js

## Bootcamp notes
-

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
