### ISSUE TITLE
JS Bootcamp - Victor Laforga

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/js-bootcamp-18-19#13]
# My Introduction

*20 jaar oud en in me vrije tijd voetbal ik graag en ben ik met vrienden*

## Name
`Victor Laforga`

## Class
`214`

## About me
`Gewoond in Belgie, Guatemala en Nicaragua`

## Goals
`Beter worden met coderen`

## Skill level
`Beginner`

## GitHub username
'victorlaforga'

## GitHub repository

[GitHub Repository Victor](https://github.com/victorlaforga/js-bootcamp)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
