### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by Ramon96** [cmda-bt/js-bootcamp-18-19#134]
# Exercises

## Name
Ramon Meijers

## Class
Tech 3

## GitHub username
Ramon96
## Bootcamp exercises
https://github.com/Ramon96/js-bootcamp

## Bootcamp notes
https://github.com/Ramon96/js-bootcamp/blob/master/notes.md

**Comment by Ramon96** [comment]
Vraagje, Ik heb l6 roads wel gemaakt, maar had niet de graph.js in me repo. Is dit de rede dat ik geen vinkje heb gekregen voor de opdracht? 

Groetjes.

**Comment by rijkvanzanten** [comment]
Het `graph.js` bestand is cruciaal voor die opdracht, anders werkt de code helemaal niet. Er zijn er maar een aantal die hem wel hebben toegevoegd.
