### ISSUE TITLE
Deiver Cortez | JS Bootcamp 18-19

### ISSUE THREAD

**Issue by deinca** [cmda-bt/js-bootcamp-18-19#14]
# My Introduction

*Hola, ik ben Deiver en kijk er naar uit om meer over JS te leren*

## Name
`Deiver Cortez`

## Class
`TECH 2`

## About me
`Geboren in Bolivia en ben sinds mijn 9de in Nederland  en ik hou van Muziek produceren`

## Goals
`Beter worden in JavaScript`

## Skill level
`Intermediate`

## GitHub username
[Github Deiver Cortez](https://github.com/Loquino)

## GitHub repository
[Repository Deiver JS Bootcamp 18-19](https://github.com/Loquino/js-bootcamp-18-19)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
