### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by NotAfr8Studio** [cmda-bt/js-bootcamp-18-19#141]
# Exercises

## Name
Mike van den Hoek

## Class
TECH3

## GitHub username
https://github.com/Fr3akyBeakyLike/Project-Tech

## Bootcamp exercises
https://github.com/Fr3akyBeakyLike/Project-Tech/tree/master/JS-bootcamp/Week%201

## Bootcamp notes
https://github.com/Fr3akyBeakyLike/Project-Tech/blob/master/JS-bootcamp/Week%201/summary1to6.js

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
