### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by ghost** [cmda-bt/js-bootcamp-18-19#142]
# My Introduction

## Name
Richay Bikhari

## Class
Tech 3

## About me
I really like doing graphic design and am fairly good at it. Aside from that, coding can also be fun once you get into it. I enjoy the problem-solving challenges that come with it and I like creating in general (systems/programs).

## Goals
My goals for this class are to take my JavaScript skills to the next level and become a real wizard.

## Skill level
I would describe myself as a intermediate JavaScript programmer.

## GitHub username
https://github.com/richayb

## GitHub repository
https://github.com/richayb/javascript-bootcamp

**Comment by dandevri** [comment]
👋 Hi Richay, the link to your repo has been added to the admin sheet. Thanks! 🎉
