### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by GiovanniKaaijk** [cmda-bt/js-bootcamp-18-19#146]
# Exercises

## Name
Giovanni Kaaijk

## Class
Tech 4

## GitHub username
https://github.com/GiovanniKaaijk/

## Bootcamp exercises
https://github.com/GiovanniKaaijk/Js-Bootcamp

## Bootcamp notes
https://github.com/GiovanniKaaijk/Js-Bootcamp/blob/master/lessen/les.js

**Comment by rijkvanzanten** [comment]
By ignoring the template repo and file structure, you've made it very hard for me to check if everything is present. Please rtfm when starting a project or class: https://github.com/cmda-bt/js-bootcamp-18-19/blob/master/getting-started.md#setting-up-your-repository
