### ISSUE TITLE
Remco Kuckelkorn js-bootcamp

### ISSUE THREAD

**Issue by Kuckelkorn** [cmda-bt/js-bootcamp-18-19#15]
# My Introduction

## Name
Remco Kuckelkorn

## Class
201 - Tech 1

## About me
Limburger

## Goals
javascript nog beter te kunnen toepassen

## Skill level
Beginner

## GitHub username
https://github.com/Kuckelkorn

## GitHub repository
https://github.com/Kuckelkorn/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
