### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Aronsmit2** [cmda-bt/js-bootcamp-18-19#16]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Aron Smit`

## Class
`206`

## About me
`Kom uit Assendelft en maak muziek als hobby.`

## Goals
`Javascript skills uitbreiden.`

## Skill level
`Beginner`

## GitHub username
`Aronsmit2, https://github.com/Aronsmit2`

## GitHub repository
`https://github.com/Aronsmit2/js-bootcamp`

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
