### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by iamDistractech** [cmda-bt/js-bootcamp-18-19#17]
# Exercises

## Name
Thijs Spijker

## Class
Tech 1

## GitHub username
[iSirThijs](https://github.com/iSirThijs)

## Bootcamp exercises
[l1-looping-a-triangle.js](https://github.com/iSirThijs/js-bootcamp/blob/master/l1-looping-a-triangle.js)
[l1-fizzbuzz.js](https://github.com/iSirThijs/js-bootcamp/blob/master/l1-fizzbuzz.js)
[l1-chessboard.js](https://github.com/iSirThijs/js-bootcamp/blob/master/l1-chessboard.js)

**Comment by dandevri** [comment]
Looking good! But, these are not all the exercises from the _first week_ only from the _first lesson_. 

Feel free to create a new issues once al the exercises from **l1, l2 a& l3** are complete.
