### ISSUE TITLE
Paulien-Lous-js-bootcamp

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/js-bootcamp-18-19#18]
# My Introduction

Mijn naam is Paulien. 

## Name
Paulien

## Class
Klas 207, project tech

## About me
Ik ben heel sportief en vind het leuk om nieuwe dingen te leren.

## Goals
Mijn doel voor dit project is om mijn technische kennis te vergroten en een stuk beter te worden in de technische vakken.

## Skill level
Ik denk dat ik val in de categorie beginner

## GitHub username
De link naar mijn GitHub: https://github.com/Plous01

## GitHub repository
De link naar mijn GitHub repository: https://github.com/Plous01/Paulien-Lous-js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

It's best not to close an issue by yourself unless you made a mistake. Teachers won't be able to see if you handed in assignments or finished exercises.
