### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Chazzers** [cmda-bt/js-bootcamp-18-19#19]
# Exercises

## Name
`Chazz Mannering`

## Class
`210`

## GitHub username
`https://github.com/Chazzers`

## Bootcamp exercises

[l1-looping-a-triangle.js](https://github.com/Chazzers/js-bootcamp/blob/master/l1-looping-a-triangle.js)
[l1-fizzbuzz.js](https://github.com/Chazzers/js-bootcamp/blob/master/l1-fizzbuzz.js)
[l1-chessboard.js](https://github.com/Chazzers/js-bootcamp/blob/master/l1-chessboard.js)

## Bootcamp notes
``

**Comment by dandevri** [comment]
Looking good! But, these are not all the exercises from the _first week_ only from the _first lesson_. 

Feel free to create a new issues once al the exercises from **l1, l2 a& l3** are complete.
