### ISSUE TITLE
js-bootcamp-18-19 - Martijn Keesmaat

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/js-bootcamp-18-19#2]
# My Introduction

## Name
Martijn Keesmaat

## Class
208 || Project Tech 2

## About me
An aspiring creative developer, part-time freelance designer && front-ender

## Goals
Get started with learning back-end and get better with JS.

## Skill level
Intermediate || Advanced

## GitHub username
MartijnKeesmaat

## GitHub repository
https://github.com/MartijnKeesmaat/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
