### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by junecha** [cmda-bt/js-bootcamp-18-19#21]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Chun Hui Xiao`

## Class
`214`

## About me
`Write something about yourself`

## Goals
`Beter worden in webdesign en wat daar bij hoort `

## Skill level
`tussen beginner en intermediate in? (e.g. beginner, intermediate, advanced)`

## GitHub username
`https://github.com/ChunningTatum`

## GitHub repository
`https://github.com/ChunningTatum/block_tech`

**Comment by dandevri** [comment]
Can you rename this repository to `js-bootcamp` instead of `block_tech`?

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
