### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by chriskes** [cmda-bt/js-bootcamp-18-19#22]
# My Introduction
25, Utrecht, Graphic Design, Sneakers.

## Name
Chris Kesarsing

## Class
203

## About me
Likes sneakers, Japan and Playstation

## Goals
Become familiar with Js in hope of becoming a fluent webdesigner

## Skill level
Beginner

## GitHub username
https://github.com/chriskes

## GitHub repository
https://github.com/chriskes/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
