### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by qiubee** [cmda-bt/js-bootcamp-18-19#23]
#  Introduction 

👋

## Name
`kevin`

## Class
`214`

## About me
:earth_africa: `11111100011`  :computer: :art: :triangular_ruler:

## Goals
`Using JavaScript without a headache`

## Skill level
`beginner`

## GitHub username
`https://github.com/qiubee`

## GitHub repository
`https://github.com/qiubee/js-bootcamp`

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
