### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/js-bootcamp-18-19#24]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Rowin

## Class
bt-1

## About me
I'm 22 years old and love to work on my car.

## Goals
To understant what I'm doing and expanding my knowledge. 

## Skill level
Beginner

## GitHub username
https://github.com/Rowin206

## GitHub repository
https://github.com/Rowin206/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
