### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Kalemis** [cmda-bt/js-bootcamp-18-19#25]
# My Introduction

## Name
Artemis Kalemis

## Class
bt-1

## About me
I am a 22 year old student living in Amsterdam with my boyfriend and my cat.

## Goals
Creating a good base for myself.

## Skill level
Beginner

## GitHub username
Kalemis

## GitHub repository
[My repository](https://github.com/Kalemis/backend-19)

**Comment by dandevri** [comment]
Can you rename this repository to `js-bootcamp`?

**Comment by Kalemis** [comment]
Renamed it!

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
