### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by kriskuiper** [cmda-bt/js-bootcamp-18-19#27]
# Exercises

## Name
`Kris Kuiper`

## Class
209 / Tech - 1

## GitHub username
https://github.com/kriskuiper

## Bootcamp exercises
https://github.com/kriskuiper/js-bootcamp

## Bootcamp notes
https://github.com/kriskuiper/js-bootcamp/tree/master/Notes

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
