### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by maaike1566** [cmda-bt/js-bootcamp-18-19#28]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Maaike Bommerson`

## Class
212

## About me
Ik snap er nu al helemaal niks meer van, maar ik vind het wel leuk

## Goals
Het overleven van dit blok en behalen van een voldoende. Wat dingen erbij leren zou ook fijn zijn.

## Skill level
Beginner

## GitHub username
maaike1566

## GitHub repository
https://github.com/cmda-bt/js-bootcamp-18-19.git

**Comment by dandevri** [comment]
> Ik snap er nu al helemaal niks meer van, maar ik vind het wel leuk

🙃

Thanks! 🎉 Added to the admin sheet.
