### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by PelleBorst** [cmda-bt/js-bootcamp-18-19#29]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
Pelle Borst

## Class
206

## About me
Ik ben Pelle. Ik woon in Leiderdorp en ik ben 18 jaar. Ik ben erg gemotiveerd voor het technische gedeelte van CMD.

## Goals
Uiteraard beter worden in HTML, CSS en JS om mezelf klaar te stomen voor mijn stage.

## Skill level
Beginner

## GitHub username
PelleBorst

## GitHub repository
https://github.com/PelleBorst/js-bootcamp.git

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
