### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by dusankaPrvulovic** [cmda-bt/js-bootcamp-18-19#3]
# My Introduction
I'm into creating imaginative, creative and playful interfaces. I'd like to learn more about code so that I'm not stuck with only being able to design.

## Name
Dusanka Prvulovic

## Class
204

## About me
`Write something about yourself`

## Goals
Trying not to get frustrated when it doesn't work out. 

## Skill level
Slightly better than a beginner

## GitHub username
https://github.com/dusankaPrvulovic

## GitHub repository
https://github.com/dusankaPrvulovic/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

Didn't you have something to say about yourself?
