### ISSUE TITLE
Repository Link 

### ISSUE THREAD

**Issue by Sanderoost** [cmda-bt/js-bootcamp-18-19#30]
## Name
Sander Oostenbrink

## Class
Class 209 - Tech 1

## About me
Im 23 years old and currently live in Castricum, Noord-Holland.

## Goals
Become better in object oriented programming and structuring my code.
And off course become better in coding with Javascript

## Skill level
Intermediate - I learned mostly the basics of coding from studying Mbo application developement at Nova college.

## GitHub username
https://github.com/Sanderoost

## GitHub repository
https://github.com/Sanderoost/blok-tech

**Comment by dandevri** [comment]
This is not the link to the bootcamp repository?

**Comment by Sanderoost** [comment]
Excuus, Had de naam veranderd vanochtend...
https://github.com/Sanderoost/js-bootcamp
