### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Sanderoost** [cmda-bt/js-bootcamp-18-19#31]
# Exercises

## Name
Sander Oostenbrink

## Class
Klas 209 - Tech 1

## GitHub username
https://github.com/Sanderoost

## Bootcamp exercises
https://github.com/Sanderoost/js-bootcamp

## Bootcamp notes
https://github.com/Sanderoost/js-bootcamp/tree/master/notes

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
