### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by cirogoud** [cmda-bt/js-bootcamp-18-19#32]
# My Introduction

## Name
Ciro Goudswaard

## Class
209 - Tech 2

## About me
I am 20 years old and live in Hilversum.

## Goals
My goals for this class are to get better at programming and learning a lot more of the world in and around programming.

## Skill level
My skill level is definitely on a beginners level. But I am aiming to become more advanced.

## GitHub username
https://github.com/cirogoud

## GitHub repository
https://github.com/cirogoud/js-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
