### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by iamDistractech** [cmda-bt/js-bootcamp-18-19#33]
# Exercises

## Name
Thijs Spijker

## Class
Tech 1

## GitHub username
[iSirThijs](https://github.com/iSirThijs)

## Bootcamp exercises
[All Exercises from Week 1](https://github.com/iSirThijs/js-bootcamp)

## Bootcamp notes
[All notes from Week 1](https://github.com/iSirThijs/js-bootcamp/tree/master/notes)

note: I haven't made notes for every chapter yet on the repository. I make handwritten nodes first and then copy them to markdown for uploading. This helps me with learning since I have to repeat and recap twice. This however goes a bit slower then directly making notes in markdown.

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
