### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/js-bootcamp-18-19#34]
# Exercises

## Name
`Stefan Gerrits`

## Class
`211 - Tech - 1`

## GitHub username
[https://github.com/StefanGerrits2](url)

## Bootcamp exercises
[https://github.com/StefanGerrits2/javascript-bootcamp](url)

## Bootcamp notes
[https://github.com/StefanGerrits2/javascript-bootcamp/blob/master/notes.md](url)

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
