### ISSUE TITLE
Week 1 - Exercises 

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/js-bootcamp-18-19#35]
# Exercises

## Name
Martijn Keesmaat

## Class
208 || Tech 1

## GitHub username
https://github.com/MartijnKeesmaat

## Bootcamp exercises
https://github.com/MartijnKeesmaat/js-bootcamp

## Bootcamp notes
https://github.com/MartijnKeesmaat/js-bootcamp

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
