### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/js-bootcamp-18-19#37]
# Exercises

## Name
Paulien Lous

## Class
Klas 207, project Tech

## GitHub username
Plous01

## Bootcamp exercises
https://github.com/Plous01/Paulien-Lous-js-bootcamp

## Bootcamp notes
Samenvatting is bijna af.

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
