### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/js-bootcamp-18-19#39]
# Exercises

## Name
`Roy Kuijper`

## Class
`211`

## GitHub username
`https://github.com/RooyyDoe`

## Bootcamp exercises
`https://github.com/RooyyDoe/js-bootcamp`

## Bootcamp notes
`https://github.com/RooyyDoe/js-bootcamp`

**Comment by dandevri** [comment]
Seems like you've put a lot of effort into understand the exercises and comming up with solutions, good code comments (in dutch?) and torough explanation.

We haven't put your exercises in the admin sheet for this week since it was empty when Rijk checked. Make sure you hand them in after week 2
