### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by emmaoudmaijer** [cmda-bt/js-bootcamp-18-19#40]
# Exercises
L1, L2,L3

## Name
Emma Oudmaijer

## Class
Tech2`

## GitHub username
Emmaoudmaijer

## Bootcamp exercises
https://github.com/emmaoudmaijer/js-bootcamp

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
