### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/js-bootcamp-18-19#41]
# Exercises

## Name
Rowin

## Class
Bt-1

## GitHub username
https://github.com/Rowin206

## Bootcamp exercises
https://github.com/Rowin206/js-bootcamp

**Comment by dandevri** [comment]
Most of the examples look good!

We're just not quite sure if `a vector type` is you own code. It's seems to be an exact copy of the solution code.

**Comment by RowinVanAmsterdam** [comment]
Thanks, that is a compliment, I think. Because I wrote the code myself and to be honest, I do not even know where the solution code can be found(?). 

Besides, I used this course as my source: 
[YouTube](https://www.youtube.com/watch?v=_cgBvtYT3fQ&index=4&t=0s&list=PLCBTL4Es6vNEoY1h4sVBYtymrzfiMFzE4)
