### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/js-bootcamp-18-19#42]
# Exercises

## Name
`Victor Laforga`

## Class
`214 || Tech 2`

## GitHub username
[Link naar profiel](https://github.com/victorlaforga)
## Bootcamp exercises
[Link naar me opdrachten](https://github.com/victorlaforga/js-bootcamp)

## Bootcamp notes
`Notities schrijf ik met pen en papier. Ze komen nog op de github.`

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!
