### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/js-bootcamp-18-19#43]
# My Introduction

## Name
`Giovanni`

## Class
`207`

## About me
`My name is Giovanni, I'm a 2nd yr CMD student, education before CMD is Interaction design at MediaCollege Amsterdam. I didn't learn enough there so i decided to learn some more`

## Goals
`Understand and get to know JS, to make some nice stuff.`

## Skill level
`Beginner`

## GitHub username
[GiovanniDw](https://github.com/GiovanniDw)

## GitHub repository
[js-Bootcamp](https://github.com/GiovanniDw/js-bootcamp)

**Comment by dandevri** [comment]
Added to the admin sheet, but you're quite late. 

I also see that you are behind schedule with the exercises, pick up the pace.
