### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by chriskes** [cmda-bt/js-bootcamp-18-19#44]
# Exercises

## Name
Chris Kesarsing
## Class
203 BT1
## GitHub username
https://github.com/chriskes

## Bootcamp exercises
https://github.com/chriskes/js-bootcamp

## Bootcamp notes
https://github.com/chriskes/js-bootcamp/blob/master/Notes.md

**Comment by dandevri** [comment]
Rijk checked your repo but it was empty at the deadline, so your grade hasn't been updated in the admin sheet. Make sure you hand-in all assignment in w-2.
