### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by qiubee** [cmda-bt/js-bootcamp-18-19#45]
# Exercises

## Name
kevin

## Class
214

## GitHub username
[qiubee](https://github.com/qiubee)

## Bootcamp exercises
[Exercises](https://github.com/qiubee/js-bootcamp)

## Bootcamp notes
[Notes](https://github.com/qiubee/eloquent-notes)

**Comment by dandevri** [comment]
The repository was checked by Rijk and your grade has been updated in the admin sheet!

Make sure you are a bit more on time next time around.
