### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by PelleBorst** [cmda-bt/js-bootcamp-18-19#46]
# Exercises

## Name
Pelle Borst

## Class
206

## GitHub username
pelleborst

## Bootcamp exercises
https://github.com/PelleBorst/js-bootcamp/tree/master/template-repo

## Bootcamp notes
https://github.com/PelleBorst/js-bootcamp/blob/master/template-repo/notes.md

**Comment by dandevri** [comment]
The exercises for the first week were not on time, will look at the exercises from w-2.
