### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by PelleBorst** [cmda-bt/js-bootcamp-18-19#47]
# Exercises

## Name
Pelle Borst

## Class
206

## GitHub username
pelleborst

## Bootcamp exercises
https://github.com/PelleBorst/js-bootcamp/tree/master/template-repo

## Bootcamp notes
https://github.com/PelleBorst/js-bootcamp/blob/master/template-repo/notes.md

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet.

Results in the next lesson!
