### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by MartijnKeesmaat** [cmda-bt/js-bootcamp-18-19#48]
# Exercises

## Name
Martijn Keesmaat

## Class
208 || Tech 1

## GitHub username
https://github.com/MartijnKeesmaat

## Bootcamp exercises
https://github.com/MartijnKeesmaat/js-bootcamp

## Bootcamp notes
https://github.com/MartijnKeesmaat/js-bootcamp

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet.

Results in the next lesson!

Notes in Notion 😍
