### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by qiubee** [cmda-bt/js-bootcamp-18-19#49]
# Exercises

## Name
kevin

## Class
214

## GitHub username
[qiubee](https://github.com/qiubee)

## Bootcamp exercises
[Exercises](https://github.com/qiubee/js-bootcamp)

## Bootcamp notes
[Notes](https://github.com/qiubee/eloquent-notes)

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. Notes are a bit empty?

Results in the next lesson!
