### ISSUE TITLE
Javascript bootcamp Stefan Gerrits

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/js-bootcamp-18-19#5]
Introductie

Ik ben Stefan Gerrits en volg het project Tech.

## Name
Stefan Gerrits

## Class
Tech 1

## About me
Ik ben 18 jaar en houd van gamen.

## Goals
Meer leren over Frontend- en Backend Development

## Skill level
Beginner

## GitHub username
https://github.com/StefanGerrits2

## GitHub repository
https://github.com/StefanGerrits2/javascript-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
