### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by maaike1566** [cmda-bt/js-bootcamp-18-19#50]
# Exercises

## Name
Maaike Bommerson

## Class
212

## GitHub username
maaike1566

## Bootcamp exercises
https://github.com/maaike1566/JS-Bootcamp/tree/master/template-repo

## Bootcamp notes
Lukt niet de foto's er in te krijgen..

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. Notes are a bit empty?

Results in the next lesson!

**Comment by dandevri** [comment]
> Lukt niet de foto's er in te krijgen..

You mean images in markdown? Have a look at this [cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images).
