### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by Sajjad0405** [cmda-bt/js-bootcamp-18-19#51]
# Exercises

## Name
Sajjad Ali

## Class
202

## GitHub username
https://github.com/Sajjad0405
## Bootcamp exercises
https://github.com/Sajjad0405/js-bootcamp

## Bootcamp notes
https://github.com/Sajjad0405/js-bootcamp

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. Where are your notes?

Results in the next lesson!
