### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/js-bootcamp-18-19#52]
# Exercises

## Name
`Roy Kuijper`

## Class
`211`

## GitHub username
`https://github.com/RooyyDoe/`

## Bootcamp exercises
`https://github.com/RooyyDoe/js-bootcamp`

## Bootcamp notes
`https://github.com/RooyyDoe/js-bootcamp/blob/master/notes.md`

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. Notes look good and your exercises have lots of code comments, looks like you really want to understand every detail of your code.

Results in the next lesson!
