### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by markschuttehva** [cmda-bt/js-bootcamp-18-19#54]
# Exercises

## Name
Mark Schutte

## Class
209

## GitHub username
Markschuttehva

## Bootcamp exercises
https://github.com/markschuttehva/javascript-bootcamp

## Bootcamp notes
https://github.com/markschuttehva/javascript-bootcamp/tree/master/Samenvattingen

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. The notes feel a bit incomplete, make sure you are consistent with language. English (commits, variable names) is preferred. 

Results in the next lesson!
