### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/js-bootcamp-18-19#55]
# Exercises

## Name
Kaan Cenik

## Class
204

## GitHub username
https://github.com/cenikk/

## Bootcamp exercises
https://github.com/cenikk/js-bootcamp

## Bootcamp notes
https://github.com/cenikk/js-bootcamp/tree/master/Notes

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet.

Results in the next lesson!
