### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [cmda-bt/js-bootcamp-18-19#57]
# Exercises

## Name
Rowin

## Class
bt-1

## GitHub username
https://github.com/Rowin206

## Bootcamp exercises
https://github.com/Rowin206/js-bootcamp

## Bootcamp notes
https://github.com/Rowin206/js-bootcamp/blob/master/notes.md

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet.

Results in the next lesson!
