### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by Plous01** [cmda-bt/js-bootcamp-18-19#58]
# Exercises

## Name
Paulien Lous

## Class
Klas 207, project Tech

## GitHub username
Plous01

## Bootcamp exercises
https://github.com/Plous01/Paulien-Lous-js-bootcamp

## Bootcamp notes
https://github.com/Plous01/Paulien-Lous-js-bootcamp

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet.

Results in the next lesson!
