### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by emmaoudmaijer** [cmda-bt/js-bootcamp-18-19#59]
# Exercises

## Name
`Add your name here`

## Class
Tech2

## GitHub username
https://github.com/emmaoudmaijer/js-bootcamp

## Bootcamp exercises
https://github.com/emmaoudmaijer/js-bootcamp/tree/master/Opdrachtenweek2

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. Notes looking good!

Results in the next lesson!
