### ISSUE TITLE
JS bootcamp Thijs Spijker

### ISSUE THREAD

**Issue by iamDistractech** [cmda-bt/js-bootcamp-18-19#6]
# My Introduction
I'm Thijs!!! I am always interested in everything. Like the things we are going to learn at blok Tech. I'am a fast learner especially when I'm interested in the subject! At home I do some gaming(but I'm not a hardcore gamer) and tinker a lot with computers and network stuff 🤓. 

I am also very eager to help others! So if there is a question, maybe I'm able to help, just ask me!!! 

## Name
Thijs Spijker

## Class
Tech 1

## About me
`Write something about yourself`

## Goals
`What are your goals for this class?`

## Skill level
Beginner, but learning fast.

## GitHub username
[iSirThijs](https://github.com/iSirThijs)

## GitHub repository
[Github JS Bootcamp repository](https://github.com/iSirThijs/js-bootcamp)

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

Feel free to help other students in Slack!
