### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by victorlaforga** [cmda-bt/js-bootcamp-18-19#60]
# Exercises

## Name
`Victor Laforga`

## Class
`Tech 2`

## GitHub username
`Add a link to your github page`

## Bootcamp exercises
[ Bootcamp](https://github.com/victorlaforga/js-bootcamp)

## Bootcamp notes
[Mijn notities](https://github.com/victorlaforga/js-bootcamp/blob/master/notes.md)

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet.

Results in the next lesson!
