### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by StefanGerrits2** [cmda-bt/js-bootcamp-18-19#61]
# Exercises

## Name
`Stefan Gerrits`

## Class
`211 / Tech - 1`

## GitHub username
[https://github.com/StefanGerrits2](url)

## Bootcamp exercises
[https://github.com/StefanGerrits2/javascript-bootcamp](url)

## Bootcamp notes
[https://github.com/StefanGerrits2/javascript-bootcamp/blob/master/notes.md](url)

**Comment by dandevri** [comment]
Your exercises have been checked and your grade is added to the admin sheet. The notes look incomplete. Just a small heads up, make sure you make correct clickable links in markdown. Your links don't point to the right repository.

Results in the next lesson!
