### ISSUE TITLE
Exercises-w2

### ISSUE THREAD

**Issue by GiovanniDw** [cmda-bt/js-bootcamp-18-19#62]
# Exercises

## Name
`Giovanni`

## Class
`207`

## GitHub username
[GiovanniDw](https://github.com/GiovanniDw/)

## Bootcamp exercises
[Bootcamp](https://github.com/GiovanniDw/js-bootcamp)

## Bootcamp notes
[Notes](https://github.com/GiovanniDw/js-bootcamp/blob/master/notes.md)

**Comment by dandevri** [comment]
These exercises from W-2 are _not on time_ so won't be counted for the final grade.
