### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by rico1136** [cmda-bt/js-bootcamp-18-19#64]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Rico Zethof`

## Class
`Tech 4`

## About me
`I am 22 years old. I just finished my internship working at VanOns a wordpress bureau. I worked with a lot of php and try to get better JavaScript using this project.`

## Goals
`Getting to use a database and storing information in it. Also working with the new es6 and getting used to the new syntax`

## Skill level
`Intermediate`

## GitHub username
`rico1136`

## GitHub repository
`https://github.com/rico1136/Project-Tech`

**Comment by dandevri** [comment]
Thanks, added the GitHub link to our admin! 🎉
