### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Wiebsonice** [cmda-bt/js-bootcamp-18-19#65]
# My Introduction

## Name
Wiebe Kremer

## Class
Tech 4

## About me
`Im a 22 Year old CMD student, Currently working at a Rich media Ad company. Passionate football player, and fanatic sneaker collector`

## Goals
`I want to broaden my javascript knowledge and try to gather more knowledge about the front-end and back-end world. To make me a more complete CMD'er`

## Skill level
`Intermediate`

## GitHub username
'GitHub username: [Wiebsonice](https://github.com/Wiebsonice)'

## GitHub repository
'[GitHub Bootcamp repository](https://github.com/Wiebsonice/Wiebe-Kremer_js-bootcamp)'

**Comment by dandevri** [comment]
Thanks, added the GitHub link to our admin sneakerhead! 🎉👟
