### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by OlafDs** [cmda-bt/js-bootcamp-18-19#68]
# My Introduction

Olaf - Hardworking CMD Student from Mijdrecht

## Name
Olaf Driessen

## Class
Tech 3

## About me
My name is Olaf. I'm 21 years old and i'm from Mijdrecht. I play waterpolo and i just finished my internship @ NewFountain in Haarlem. I like to chill with my friends and sometimes i play some videogames.

## Goals
My goals are that i become more familiar with JavaScript, that i can create beautiful stuff with JavaScript and that i have more knowlegde about JavaScript.

## Skill level
My skill level would be intermediate. I know the basics, but not familiar with the advanced stuff.

## GitHub username
OlafDs

## GitHub repository
https://github.com/OlafDs/block-tech

**Comment by dandevri** [comment]
Thanks, added the link to your repo in the admin sheet! 🎉

What video games do you play? 🎮

**Comment by dandevri** [comment]
You might consider changing the repository name to `js-bootcamp`.
