### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by ccdejene** [cmda-bt/js-bootcamp-18-19#69]
# My Introduction

## Name
`Eyob Westerink`

## Class
TECH3

## About me
i like to design and develop websites.
I have worked as a front-end developer for various companies and I have established a online sneakerplatform.

## Goals
Expand knowledge

## Skill level
Intermediate / advanced

## GitHub username
https://github.com/EyobDejene

## GitHub repository
https://github.com/EyobDejene/js-bootcamp

**Comment by dandevri** [comment]
Thanks, added the link to your repo to the admin sheet sneakerhead! 🎉👟
