### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by RooyyDoe** [cmda-bt/js-bootcamp-18-19#7]
# My Introduction

*A small heads up before you begin typing, never mention your name in combination with your HvA student number in public.*

## Name
`Roy Kuijper`

## Class
`Klas 211`

## About me
`Something about myself ( PC Gamer ) i dont know..`

## Goals
`Learn more about FE, BE and start my intership with more experience.`

## Skill level
`beginner/intermediate`

## GitHub username
`https://github.com/RooyyDoe`

## GitHub repository
`https://github.com/RooyyDoe/js-bootcamp`

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
