### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Ramon96** [cmda-bt/js-bootcamp-18-19#70]
# My Introduction

## Name
Ramon Meijers.

## Class
Tech 3

## About me
Hi I'm Ramon. Still a student, but one with a passion! Getting the result I desire does put on a smile on my face. Learning all the cool and new stuff makes my blood rush.

## Goals
My main goal is to be able to write clean and readable code. An plus would be to be able to consider myself an improved front-end developer at the end of this course.

## Skill level
I would consider myself an beginner/Intermediate. I have some experiences with code, but there is room for improvement.

## GitHub username
https://github.com/Ramon96

## GitHub repository
https://github.com/Ramon96/js-bootcampRepository

**Comment by dandevri** [comment]
Thanks, added the link to your repo to the admin sheet! 🎉
