### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by CountNick** [cmda-bt/js-bootcamp-18-19#71]
# My Introduction

## Name
Nick Meijer

## Class
TECH3

## About me
Hi, my name is Nick. I'd call myself a creative person with a passion for horror and code.

## Goals
Get more knowledge of programming and back end coding.

## Skill level
 I'd say my skill level is somewhere between beginner and intermediate.

## GitHub username
https://github.com/countnick

## GitHub repository
https://github.com/CountNick/JS-Bootcamp

**Comment by dandevri** [comment]
Thanks, added the link to your repo to the admin sheet! 🎉
