### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by TheKevSter35** [cmda-bt/js-bootcamp-18-19#72]
# My Introduction

Kevin - CMD student from Amsterdam

## Name
Kevin Curi

## Class
Tech 4

## About me
My name is Kevin. I'm 24 years old and i'm from Amsterdam. I just finished my intership @ Bikkelhart and in mei i'm going to work there. Also i like to play videogames in free time. 

## Goals
My goals: That i have more knowledge with JS en can create nice stuff with it/

## Skill level
My skill level would be intermediate. I know the basics

## GitHub username
`TheKevSter-NL
https://github.com/TheKevSter-NL

## GitHub repository
https://github.com/TheKevSter-NL/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi kevin, is this the right link? I see another repository on your accounts that's called `js-bootcamp`?

**Comment by TheKevSter35** [comment]
> 👋 Hi kevin, is this the right link? I see another repository on your accounts that's called `js-bootcamp`?

Hi Danny, js-boot camp is the right one. I forgot to change it in this issue
