### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Roelmeijns** [cmda-bt/js-bootcamp-18-19#73]
# My Introduction

## Name
Roel Meijns

## Class
Tech 3

## About me
I'm Roel Meijns 23 years old and in my second year of Communication Multimedia Design.

## Goals
Master the basics and improve my tech skills.

## Skill level
In between beginner and intermediate.

## GitHub username
Roelmeijns

## GitHub repository
https://github.com/Roelmeijns/js-bootcamp.git

**Comment by dandevri** [comment]
👋 Hi Roel, the link to your repo has been added to the admin sheet. Thanks! 🎉
