### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by TheKevSter35** [cmda-bt/js-bootcamp-18-19#75]
# Exercises

## Name
Kevin Curi

## Class
TECH 4

## GitHub username
https://github.com/TheKevSter-NL

## Bootcamp exercises
https://github.com/TheKevSter-NL/js-bootcamp

https://github.com/TheKevSter-NL/js-bootcamp/blob/master/triangle.js
https://github.com/TheKevSter-NL/js-bootcamp/blob/master/fizzbuzz.js
https://github.com/TheKevSter-NL/js-bootcamp/blob/master/chessboard.js

https://github.com/TheKevSter-NL/js-bootcamp/blob/master/mininum.js
https://github.com/TheKevSter-NL/js-bootcamp/blob/master/beancouting.js
https://github.com/TheKevSter-NL/js-bootcamp/blob/master/sum-of-range.js

https://github.com/TheKevSter-NL/js-bootcamp/blob/master/flatten.js
https://github.com/TheKevSter-NL/js-bootcamp/blob/master/vector.js

## Bootcamp notes
https://github.com/TheKevSter-NL/js-article

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
