### ISSUE TITLE
https://github.com/aaraar/js-bootcamp

### ISSUE THREAD

**Issue by bazottie** [cmda-bt/js-bootcamp-18-19#76]
# My Introduction

## Name
`Bas de Greeuw`

## Class
`212, tech-4`

## About me
`Second year CMD student, chairman of IAM Core and always down for a good discussion (preferably with a beer)`

## Goals
`Improve my knowledge and skill with the basics of webdevelopment and acquire more in-depth knowledge of how web technologies work`

## Skill level
`Intermediate`

## GitHub username
[aaraar](https://github.com/aaraar)

## GitHub repository
[bt-bas-g](https://github.com/aaraar/js-bootcamp)

**Comment by dandevri** [comment]
👋 Hi Bas, the link to your repo has been added to the admin sheet. Thanks! 🎉

You might consider changing the repo name to `js-bootcamp`.
