### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by bazottie** [cmda-bt/js-bootcamp-18-19#77]
# Exercises

## Name
`Bas de Greeuw`

## Class
`tech-4`

## GitHub username
[aaraar](https://github.com/aaraar)

## Bootcamp exercises
[Triangle](https://github.com/aaraar/js-bootcamp/blob/master/week1/triangle/script.js)
[Fizzbuzz](https://github.com/aaraar/js-bootcamp/blob/master/week1/fizzbuzz/script.js)
[Chessboard](https://github.com/aaraar/js-bootcampg/blob/master/week1/chessboard/script.js)
[Minimum](https://github.com/aaraar/js-bootcamp/blob/master/week1/minimum/script.js)
[Beancounting](https://github.com/aaraar/js-bootcamp/blob/master/week1/beancounting/script.js)
[The Sum of Range](https://github.com/aaraar/js-bootcamp/blob/master/week1/sumRange/script.js)
[Flattening](https://github.com/aaraar/js-bootcamp/blob/master/week1/flattening/script.js)
[A Vector type](https://github.com/aaraar/js-bootcamp/blob/master/week1/vector/script.js)

## Bootcamp notes
[Notes](https://github.com/aaraar/js-bootcamp/tree/master/week1/notes)

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
