### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Mokerstier** [cmda-bt/js-bootcamp-18-19#78]
# My Introduction

## Name
Wouter van der Heijde

## Class
Tech-4

## About me
27 y/o Male living in Bigpants (Grootebroek)

## Goals
My goals for this class are getting familiar with backend and being able to set up my own database. So in the future I can create my own websites/applications from front-end to back-end.

## Skill level
intermediate

## GitHub username
Mokerstier

## GitHub repository
https://github.com/Mokerstier/blokTechBootcamp

**Comment by dandevri** [comment]
👋 Hi Wouter, the link to your repo has been added to the admin sheet. Thanks! 🎉 Bigpants 👖

You might consider putting every exercise in a different `.js` file, that's a bit easier for teachers to check.
