### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by CountNick** [cmda-bt/js-bootcamp-18-19#79]
# Exercises

## Name
Nick Meijer

## Class
TECH3

## GitHub username
https://github.com/CountNick

## Bootcamp exercises
https://github.com/CountNick/JS-Bootcamp/tree/master/Week1

## Bootcamp notes
`Add a link to your notes in your repository`

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
