### ISSUE TITLE
Javascript Bootcamp Mark Schutte

### ISSUE THREAD

**Issue by markschuttehva** [cmda-bt/js-bootcamp-18-19#8]
# My Introduction
Born to be awesome not perfect

## Name
Mark Schutte

## Class
209

## About me
I enjoy playing games, watching movies and hang out with my friends.

## Goals
I would love to learn more about coding it's like learning a new language.

## Skill level
Somewhere between beginner / intermediate.

## GitHub username
https://github.com/markschuttehva

## GitHub repository
https://github.com/markschuttehva/javascript-bootcamp

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.
