### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Mokerstier** [cmda-bt/js-bootcamp-18-19#80]
# Exercises

## Name
Wouter van der Heijde

## Class
Tech-4

## GitHub username
[https://github.com/Mokerstier/blokTechBootcamp](url)

## Bootcamp exercises
[https://github.com/Mokerstier/blokTechBootcamp/blob/master/Exercises.js](url)

## Bootcamp notes
Note's behind exercises

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
