### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by TomasStolp** [cmda-bt/js-bootcamp-18-19#81]
# Exercises
All exercises of week 1
## Name
Tomas Stolp

## Class
Tech 3

## GitHub username
TomasS666

## Bootcamp exercises
https://github.com/TomasS666/JS-Bootcamp-Exercises

I left comments behind in the code

**Comment by TomasStolp** [comment]
I added the remaining 3 exercises to my repository.

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
