### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Roelmeijns** [cmda-bt/js-bootcamp-18-19#82]
# Exercises

## Name
Roel Meijns

## Class
Tech 3

## GitHub username
Roelmeijns

## Bootcamp exercises
https://github.com/Roelmeijns/js-bootcamp

## Bootcamp notes
Notes written on paper!

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
