### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Dejorden94** [cmda-bt/js-bootcamp-18-19#83]
# Exercises

## Name
Dejorden Moerman

## Class
Tech 3 / 212

## GitHub username
Dejorden94

## Bootcamp exercises
https://github.com/Dejorden94/blockTech2019

## Bootcamp notes
`Add a link to your notes in your repository`

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
