### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by joanpadolina** [cmda-bt/js-bootcamp-18-19#84]
# Exercises
Triangle Loop
FizzBuzz
ChessBoard

## Name
Joan Padolina

## Class
Block tech 4 // 207

## GitHub username
https://github.com/joanpadolina

## Bootcamp exercises
https://github.com/joanpadolina/js_bootcamp2019

## Bootcamp notes
3 Opdrachten uit hoofdstuk 2

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
