### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by LarsBreuren** [cmda-bt/js-bootcamp-18-19#86]
# Exercises

## Name
`Lars Breuren`

## Class
`206 - tech4`

## GitHub username
`https://github.com/LarsBreuren`

## Bootcamp exercises
`https://github.com/LarsBreuren/BlokTech`

## Bootcamp notes
`404`

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
