### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by ccdejene** [cmda-bt/js-bootcamp-18-19#87]
# Exercises

Triangle Loop
FizzBuzz
ChessBoard
Minimum
BeanCounting
The Sum of a Range
Flattening
A vector type

## Name
Eyob Westerink

## Class
TECH3

## GitHub username
https://github.com/EyobDejene

## Bootcamp exercises
https://github.com/EyobDejene/js-bootcamp

## Bootcamp notes
none

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
