### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by woutarb** [cmda-bt/js-bootcamp-18-19#88]
# Exercises

## Name
Wouter Bijnsdorp

## Class
Tech 3

## GitHub username
WouterBijns
https://github.com/wouterBijns

## Bootcamp exercises
https://github.com/wouterBijns/BootCampHomework/tree/master/homeworkWeek1

## Bootcamp notes
Most of the stuff was do-able.

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
