### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by woutarb** [cmda-bt/js-bootcamp-18-19#89]
# My Introduction

## Name
Wouter Bijnsdorp

## Class
Tech 3

## About me
Metalhead, tabletoprpg, book, comic en videogame nerd.

## Goals
Betere grip op al bekende stof en opdoen van ervaring en kennis over nieuwe stof die ik nog niet ken

## Skill level
Beginner

## GitHub username
WouterBijns
https://github.com/wouterBijns/

## GitHub repository
https://github.com/wouterBijns/BootCampHomework

**Comment by dandevri** [comment]
👋 Hi Wouter, the link to your repo has been added to the admin sheet. Thanks! 🎉

What video games do you play? 🎮

**Comment by woutarb** [comment]
Currently mostly Rainbow six siege, Ghost Recon Wildlands, wolfenstein 2, shadow of war.
