### ISSUE TITLE
JS Bootcamp Kaan Cenik

### ISSUE THREAD

**Issue by cenikk** [cmda-bt/js-bootcamp-18-19#9]
# My Introduction

Hi and welcome

## Name
Kaan Cenik

## Class
204

## About me
I'm a 21 years old student living in Amsterdam

## Goals
Extend my skills overall

## Skill level
Intermediate

## GitHub username
cenikk
https://github.com/cenikk

## GitHub repository
js-bootcamp
https://github.com/cenikk/js-bootcamp.git

**Comment by dandevri** [comment]
Thanks! 🎉 Added to the admin sheet.

You're repo does feel a bit emty.. :)
