### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by SqueezyDough** [cmda-bt/js-bootcamp-18-19#92]
# My Introduction

## Name
Leroy van Biljouw

## Class
Tech 4

## About me
25 jaar
Woon in Zwaag
2 katten

## Goals
Beter begrip van theorie van js.

## Skill level
Intermediate
vooropleiding: MBO applicatieontwikkelaar

## GitHub username
https://github.com/SqueezyDough

## GitHub repository
https://github.com/SqueezyDough/JS-Bootcamp

**Comment by dandevri** [comment]
👋 Hi Leroy, the link to your repo has been added to the admin sheet. Thanks! 🎉

Do you have a picture of your cats? 🐱
