### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by harmvv** [cmda-bt/js-bootcamp-18-19#93]
# My Introduction

## Name
Harm van Versveld

## Class
203

## About me
Ik heb bij het circus gezeten

## Goals
Beter worden in programmeren en het vooral beter begrijpen.

## Skill level
Ik ben een beginner, ik krijg wel veel dingen voor elkaar maar wil het allemaal beter leren begrijpen.

## GitHub username
https://github.com/harmvv

## GitHub repository
https://github.com/harmvv/bootcamp

**Comment by dandevri** [comment]
👋 Hi Harm, the link to your repo has been added to the admin sheet. Thanks! 🎉
