### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by harmvv** [cmda-bt/js-bootcamp-18-19#94]
# Exercises

## Name
Harm van Verseveld

## Class
203

## GitHub username
https://github.com/harmvv

## Bootcamp exercises
https://github.com/harmvv/bootcamp

**Comment by harmvv** [comment]
Tweede deel van het huiswerk toegevoegd

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
