### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by Ramon96** [cmda-bt/js-bootcamp-18-19#95]
# Exercises
* [l1-chessboard.js](https://github.com/Ramon96/js-bootcamp/blob/master/l1-chessboard.js)
* [l1-fizzbuzz.js](https://github.com/Ramon96/js-bootcamp/blob/master/l1-fizzbuzz.js)
* [l1-looping-a-triangle.js](https://github.com/Ramon96/js-bootcamp/blob/master/l1-looping-a-triangle.js)
* [l2-bean-counting.js](https://github.com/Ramon96/js-bootcamp/blob/master/l2-bean-counting.js)
* [l2-minimum.js](https://github.com/Ramon96/js-bootcamp/blob/master/l2-minimum.js)
* [l2-sum-of-a-range.js](https://github.com/Ramon96/js-bootcamp/blob/master/l2-sum-of-a-range.js)
* [l3-flattening.js](https://github.com/Ramon96/js-bootcamp/blob/master/l3-flattening.js)
* [l3-vector-type.js](https://github.com/Ramon96/js-bootcamp/blob/master/l3-vector-type.js)

## Name
Ramon Meijers

## Class
Tech 3

## GitHub username
Ramon96

## Bootcamp exercises
https://github.com/Ramon96/js-bootcamp

## Bootcamp notes
https://github.com/Ramon96/js-bootcamp/blob/master/notes.md

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
