### ISSUE TITLE
Exercises-w1

### ISSUE THREAD

**Issue by MarcKunst** [cmda-bt/js-bootcamp-18-19#96]
# Exercises

## Name
Marc Kunst

## Class
Tech 4

## GitHub username
MarcKunst

## Bootcamp exercises
(https://github.com/MarcKunst/js-bootcamp)

## Bootcamp notes
Komen er aan

**Comment by dandevri** [comment]
👋 Thanks, we'll look at the exercises from `exercises-w2` for your final grade!
