### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by charder001** [cmda-bt/js-bootcamp-18-19#97]
# My Introduction

## Name
Rick Chardet

## Class
Tech3

## About me
Hoopt dit blok te overleven.

## Goals
Huidige kennis checken en verbreden.

## Skill level
Beginner - intermediate

## GitHub username
charder001

## GitHub repository
https://github.com/charder001/js-bootcamp

**Comment by dandevri** [comment]
👋 Hi Rick, the link to your repo has been added to the admin sheet. Thanks! 🎉
